###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "TESTE_0001",
    "price": 1000.01
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "TESTE_0002",
    "price": 2000.02
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "TESTE_0003",
    "price": 3000.03
}