

function createPaginationSchema(){}

export {createPaginationSchema}


PAREI AQUI, TEM QUE FAZER ESSE HELPER PARA CRIAR O SCHEMA DO PAGINATION SEPARADO QUE PODERÁ SER UTILIZADO POR MAIS DE UMA ROTA (USERLIST, POSTLIST,ETC...)

DEPOIS FAZER OU ATUALIZAR O IUSERLISTCONTROLLER PARA FAZER SOMENTE OS QUERY PARAMS ("name/email/role/...") E EXPORTAR O MERGE DOS DOIS SCHEMAS