import { DomainError } from "@/core/shared/errors/domain/domain-error";

export class ExpenseIdEmptyError extends DomainError {}
export class InvalidExpenseIdError extends DomainError {}
export class ExpenseNameTooShortError extends DomainError {}
export class ExpenseNameTooLongError extends DomainError {}
export class ExpenseNameEmptyError extends DomainError {}
export class ExpenseNameWhitespaceError extends DomainError {}
export class InvalidExpenseStatusError extends DomainError {}
export class InvalidExpenseStatusTransitionError extends DomainError {}
export class InstallmentIdEmptyError extends DomainError {}
export class InvalidInstallmentIdError extends DomainError {}
export class InstallmentNumbersMustBeIntegersError extends DomainError {}
export class InstallmentNumbersMustBePositiveError extends DomainError {}
export class InstallmentCurrentExceedsTotalError extends DomainError {}
export class InstallmentTotalTooHighError extends DomainError {}
export class InstallmentAlreadyCompleteError extends DomainError {}
export class MoneyAmountNegativeError extends DomainError {}
export class InvalidMoneyAmountError extends DomainError {}
export class MoneyCurrencyEmptyError extends DomainError {}
export class InvalidMoneyCurrencyError extends DomainError {}
export class MoneyCentsMustBeIntegerError extends DomainError {}
export class MoneyCentsNegativeError extends DomainError {}
export class MoneyNegativeResultError extends DomainError {}
export class MoneyInvalidMultiplicationFactorError extends DomainError {}
export class MoneyNegativeMultiplicationFactorError extends DomainError {}
export class MoneyInvalidDivisionFactorError extends DomainError {}
export class MoneyDivisionByZeroError extends DomainError {}
export class MoneyNegativeDivisorError extends DomainError {}
export class MoneyInvalidSplitQuantityError extends DomainError {}
export class MoneyEmptyRatiosError extends DomainError {}
export class MoneyZeroTotalRatioError extends DomainError {}
export class MoneyNegativeRatioError extends DomainError {}
export class MoneyCurrencyMismatchError extends DomainError {}
export class PaymentScheduleInvalidDateError extends DomainError {}
export class PaymentScheduleInvalidPeriodError extends DomainError {}
export class PaymentScheduleExpirationOutsidePeriodError extends DomainError {}
export class PaymentScheduleDateTooEarlyError extends DomainError {}
export class PaymentScheduleDateTooFarInFutureError extends DomainError {}
export class TagTooShortError extends DomainError {}
export class TagTooLongError extends DomainError {}
export class TagInvalidFormatError extends DomainError {}
export class TagEmptyError extends DomainError {}
export class TagsLimitExceededError extends DomainError {}
export class TagsCannotAddMoreError extends DomainError {}
